

  version: "3.9"
  services:
    web:
      build: .
      ports:
        - "8081:8081"
    mysqldb:
     image: "mysql:latest"
     ports:
       - "3307:3306"
     environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demodb

